export const CONFIRMACIONES_ACTION_TYPES = {
    CREATION_CONFIRMACION_START: 'confirmacion/CREATION_CONFIRMACION_START',
    CREATION_CONFIRMACION_SUCCESS: 'confirmacion/CREATION_CONFIRMACION_SUCCESS',
    CREATION_CONFIRMACION_FAILED: 'confirmacion/CREATION_CONFIRMACION_FAILED',

    GET_CONFIRMACIONES_SUCCESS: 'confirmaciones/GET_CONFIRMACIONES_SUCCESS',
    GET_CONFIRMACIONES_START: 'confirmaciones/GET_CONFIRMACIONES_START',
    GET_CONFIRMACIONES_FAILED: 'confrimaciones/GET_CONFIRMACIONES_FAILED',

    UPDATE_CONFIRMACION_START: 'confirmaicon/UPDATE_CONFIRMACION_START',
    UPDATE_CONFIRMACION_SUCCESS: 'confirmaicon/UPDATE_CONFIRMACION_SUCCESS',
    UPDATE_CONFIRMACION_FAILED: 'confirmaicon/UPDATE_CONFIRMACION_FAILED',

    DELETE_CONFIRMACION_START: 'confirmaicon/DELETE_CONFIRMACION_START',
    DELETE_CONFIRMACION_SUCCESS: 'confirmaicon/DELETE_CONFIRMACION_SUCCESS',
    DELETE_CONFIRMACION_FAILED: 'confirmaicon/DELETE_CONFIRMACION_FAILED',


  };
  