export const CONFIRMACIONES_ACTION_TYPES = {
    CREATION_CONFIRMACION_START: 'confirmacion/CREATION_CONFIRMACION_START',
    CREATION_CONFIRMACION_SUCCESS: 'confirmacion/CREATION_CONFIRMACION_SUCCESS',
    CREATION_CONFIRMACION_FAILED: 'confirmacion/CREATION_CONFIRMACION_FAILED',

    GET_CONFIRMACIONES_SUCCESS: 'confirmaciones/GET_CONFIRMACIONES_SUCCESS',
    GET_CONFIRMACIONES_START: 'confirmaciones/GET_CONFIRMACIONES_START',
    GET_CONFIRMACIONES_FAILED: 'confrimaciones/GET_CONFIRMACIONES_FAILED',

  };
  