export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
  SIGN_UP_START: 'user/SIGN_UP_START',
  SIGN_UP_SUCCESS: 'user/SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'user/SIGN_UP_FAILED',
  SIGN_OUT_START: 'user/SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',

  UPDATE_PASSWORD_START: 'user/UPDATE_PASSWORD_START',
  UPDATE_PASSWORD_SUCCESS: 'user/UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILED: 'user/UPDATE_PASSWORD_FAILED',

  SEND_EMAIL_RECOVER_PASSWORD_START: 'user/SEND_EMAIL_RECOVER_PASSWORD_START',
  SEND_EMAIL_RECOVER_PASSWORD_SUCCESS: 'user/SEND_EMAIL_RECOVER_PASSWORD_SUCCESS',
  SEND_EMAIL_RECOVER_PASSWORD_FAILED: 'user/SEND_EMAIL_RECOVER_PASSWORD_FAILED',

  RESET_USER_ERROR: 'user/RESET_USER_ERROR',

  GET_CURRENT_USER_AUTHENTICATED: 'user/GET_CURRENT_USER_AUTHENTICATED',

  GET_USERS_START: 'users/GET_USERS_START',
  GET_USERS_SUCCESS: 'users/GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'users/GET_USERS_FAILED',


  GET_FEATURE_FLAGS_START: 'flags/GET_FEATURE_FLAGS_START',
  GET_FEATURE_FLAGS_SUCCESS: 'flags/GET_FEATURE_FLAGS_SUCCESS',
  GET_FEATURE_FLAGS_FAILED: 'flags/GET_FEATURE_FLAGS_FAILED',

};
