export const NOTIFICACIONES_ACTION_TYPES = {

    CREATE_NOTIFICACION_START: 'notificacion/CREATE_NOTIFICACION_START',
    CREATE_NOTIFICACION_SUCCESS: 'notificacion/CREATE_NOTIFICACION_SUCCESS',
    CREATE_NOTIFICACION_FAILED: 'notificacion/CREATE_NOTIFICACION_FAILED',

    GET_NOTIFICACIONES_START: 'notificacion/GET_NOTIFICACIONES_START',
    GET_NOTIFICACIONES_SUCCESS: 'notificacion/GET_NOTIFICACIONES_SUCCESS',
    GET_NOTIFICACIONES_FAILED: 'notificacion/GET_NOTIFICACIONES_FAILED',

    UPDATE_NOTIFICACION_START: 'notificacion/UPDATE_NOTIFICACION_START',
    UPDATE_NOTIFICACION_SUCCESS: 'notificacion/UPDATE_NOTIFICACION_SUCCESS',
    UPDATE_NOTIFICACION_FAILED: 'notificacion/UPDATE_NOTIFICACION_FAILED',

    DELETE_NOTIFICACION_START: 'notificacion/DELETE_NOTIFICACION_START',
    DELETE_NOTIFICACION_SUCCESS: 'notificacion/DELETE_NOTIFICACION_SUCCESS',
    DELETE_NOTIFICACION_FAILED: 'notificacion/DELETE_NOTIFICACION_FAILED',

    SET_NOTIFICACION_CONFIRMACION_START: 'notificacion/SET_NOTIFICACION_CONFIRMACION_START',
    SET_NOTIFICACION_CONFIRMACION_SUCCESS: 'notificacion/SET_NOTIFICACION_CONFIRMACION_SUCCESS',
    SET_NOTIFICACION_CONFIRMACION_FAILED: 'notificacion/SET_NOTIFICACION_CONFIRMACION_FAILED',

  };
  